# Generated by Django 5.1.2 on 2024-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.FileField(default='images/default.jpg', upload_to='images/')),
                ('is_edible', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('IN', 'Indoor Plants'), ('OUT', 'Outdoor Plants'), ('FV', 'Fruit & Vegetable'), ('SC', 'Succulents & Cacti'), ('FL', 'Flowers')], default='IN', max_length=64)),
            ],
        ),
    ]
